
log_format = "full"

data_directory = "data"
da_read_from = "127.0.0.1:4141"

rest_server_port = 4000
rest_server_max_body_size = 10_485_760 # 10 MB
node_url = "http://localhost:4321"


da_address = "127.0.0.1:4141"

buffer_blocks = 0
max_txs_per_proof = 100
tx_working_window_size = 400
